[project]
name = "deepvision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepface>=0.0.95",
    "dotenv>=0.9.9",
    "supabase>=2.24.0",
    "tf-keras>=2.20.1",
]
